name = "neopost"
license = "GPL-3.0"
licenselink = "https://github.com/salatine/neopost/LICENSE"
description = "neopost is a minimalist, customizable theme for personal blogs, inspired by the aesthetics of neocities. it allows for multilingual, flexible content management and easy customization of styles through simple configuration."

homepage = "https://github.com/salatine/neopost"

demosite = "https://neopost.neocities.org"

tags = ["blog", "personal", "responsive", "light", "dark", "multilingual"]

authors = [
  { name = "salatine", homepage = "https://github.com/salatine" },
  { name = "cartola", homepage = "https://github.com/Carto1a" }
]
